baseurl = "https://example.com/"
languageCode = "en-US"
title = "FLCA"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "flcalogo.png"
  author = "FLCA"
  description = "Family Law and Cannabis Alliance"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "username"
  Email         = "email@example.com"
  Twitter       = "username"
  LinkedIn      = "username"
  Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "Policy"
  weight = 100
  identifier = "policy"
  url = "/policy/"
[[menu.main]]
  name = "Legal Resources"
  identifier = "legal-resources"
  weight = 200
  url = "/legal-resources/"
[[menu.main]]
  name = "Media"
  identifier = "media"
  weight = 300
  url = "/media/"
[[menu.main]]
  name = "Need Help?"
  identifier = "help"
  weight = 400
  url = "/help/"
[[menu.main]]
  name = "Writing"
  identifier = "writing"
  weight = 500
  url = "/writing/"
[[menu.main]]
  name = "Links"
  identifier = "links"
  weight = 600
  url = "/links/"
[[menu.main]]
  name = "Board"
  identifier = "board"
  weight = 700
  url = "/board/"
