baseurl = "https://flca.netlify.com/"
languageCode = "en-US"
title = "FLCA"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "flcalogo.png"
  author = "Family Law and Cannabis Alliance"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "email@example.com"

## Main Menu
[[menu.main]]
  name = "Policy"
  weight = 100
  identifier = "policy"
  url = "/policy/"
[[menu.main]]
  name = "Legal Network"
  identifier = "legal-network"
  weight = 200
  url = "/legal-network/"
[[menu.main]]
  name = "Media"
  identifier = "media"
  weight = 300
  url = "/media/"
[[menu.main]]
  name = "Need help?"
  identifier = "help"
  weight = 400
  url = "/help/"
[[menu.main]]
  name = "Writing"
  identifier = "writing"
  weight = 500
  url = "/writing/"
[[menu.main]]
  name = "Links"
  identifier = "links"
  weight = 600
  url = "/links/"
[[menu.main]]
  name = "Board"
  identifier = "board"
  weight = 700
  url = "/board/"
